services:
  postgres:
    image: postgres:16
    container_name: onibus_express_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: onibus_express
      POSTGRES_USER: onibus
      POSTGRES_PASSWORD: onibus123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
